// vue/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router';
import 'ckbox/dist/styles/ckbox.css';
</script>

<template>
    <div id="app">
        <h1>CKBox – Vue.js Development Sample</h1>

        <ul className="route__list">
            <li className="route__list-item">
                <RouterLink to="/inline">Inline</RouterLink>
            </li>
            <li className="route__list-item">
                <RouterLink to="/dialog">Dialog</RouterLink>
            </li>
            <li className="route__list-item">
                <RouterLink to="/custom-event">With custom event</RouterLink>
            </li>
        </ul>

        <RouterView></RouterView>
    </div>
</template>

<style scoped>
body {
    max-width: 800px;
    margin: 20px auto;
}

.route__list {
    list-style-type: none;
}
</style>

// angular/src/app/app.component.ts
import { Component, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
    selector: 'app-root',
    standalone: true,
    imports: [CommonModule, RouterOutlet, RouterLink],
    templateUrl: './app.component.html',
    styleUrl: './app.component.css'
})
export class AppComponent {
    title = 'angular';
}

<h1>CKBox – Angular Development Sample</h1>

<ul class="route__list">
    <li class="route__list-item"><a routerLink="/inline">Inline</a></li>
    <li class="route__list-item"><a routerLink="/dialog">Dialog</a></li>
    <li class="route__list-item">
        <a routerLink="/custom-event">With custom event</a>
    </li>
</ul>

<router-outlet></router-outlet>
