// angular/src/app/dialog-sample/dialog-sample.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import * as CKBox from 'ckbox';

@Component({
    selector: 'ckbox-dialog-sample',
    templateUrl: './dialog-sample.component.html',
    styleUrls: ['./dialog-sample.component.css']
})
export class DialogSampleComponent {
    @ViewChild('ckbox') ckboxRoot?: ElementRef;
    isOpen = false;

    // eslint-disable-next-line @typescript-eslint/no-empty-function
    unmountCallback = () => {};

    toggleDialog() {
        if (this.isOpen) {
            this.isOpen = false;
            this.unmountCallback();
        } else {
            const { unmount } = CKBox.mount(this.ckboxRoot?.nativeElement, {
                tokenUrl: 'https://your.token.url/',
                dialog: {
                    height: 600,
                    width: 800,
                    onClose: () => {
                        this.isOpen = false;
                    }
                }
            });

            this.isOpen = true;
            this.unmountCallback = unmount;
        }
    }
}

<section>
    <h3>Dialog CKBox</h3>
    <button (click)="toggleDialog()">Toggle dialog</button>
    <div #ckbox class="ckbox-container"></div>
</section>

// vue/src/views/DialogSampleComponent.vue
<template>
    <section>
        <h3>Dialog CKBox</h3>
        <button @click="toggleDialog">Toggle dialog</button>
        <div ref="ckbox"></div>
    </section>
</template>

<script setup lang="ts">
import * as CKBox from 'ckbox';
import { reactive, ref } from 'vue';

const ckbox = ref();
const state = reactive({ isOpen: false, unmountCallback: () => {} });

function toggleDialog() {
    if (state.isOpen) {
        state.isOpen = false;
        state.unmountCallback();
    } else {
        const { unmount } = CKBox.mount(ckbox.value, {
            tokenUrl: 'https://your.token.url',
            dialog: {
                height: 600,
                width: 800,
                onClose: () => {
                    state.isOpen = false;
                }
            }
        });

        state.isOpen = true;
        state.unmountCallback = unmount;
    }
}
</script>

<style scoped></style>
