// angular/src/app/inline-sample/inline-sample.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import * as CKBox from 'ckbox';

@Component({
    selector: 'ckbox-inline-sample',
    templateUrl: './inline-sample.component.html',
    styleUrls: ['./inline-sample.component.css']
})
export class InlineSampleComponent implements AfterViewInit {
    @ViewChild('ckbox') ckboxRoot?: ElementRef;

    ngAfterViewInit(): void {
        CKBox.mount(this.ckboxRoot?.nativeElement, {
            tokenUrl: 'https://dev.ckbox.io/demo/token/'
        });
    }
}

<section>
    <h3>Inline CKBox</h3>
    <div #ckbox class="ckbox-container"></div>
</section>

// vue/src/views/InlineSampleComponent.vue
<template>
    <section>
        <h3>Inline CKBox</h3>
        <div ref="ckbox" className="ckbox-container"></div>
    </section>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import * as CKBox from 'ckbox';

const ckbox = ref();

onMounted(() => {
    CKBox.mount(ckbox.value, {
        tokenUrl: 'https://dev.ckbox.io/demo/token/'
    });
});
</script>

<style scoped>
.ckbox-container {
    height: 600px;
    width: 800px;
}
</style>
